packages:
  - 'packages/*'
  - 'crates/*'
allowBuilds:
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@mizdra/*'
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - vitest
  - '@vitest/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vite-plus: 0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vitest: 4.1.10
  '@vitest/coverage-v8': 4.1.10
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
